name: Pull Request tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build

      - name: Install packages
        run: nix-env -i hugo yarn python38Packages.weasyprint gitFull linkchecker perlPackages.Po4a python3

      - name: npm Install
        run: cd themes/hugo-darktable-docs-theme/assets/ && yarn install

      - name: Build the static site
        run:  hugo --baseURL http://localhost:8080

      - name: Build PDF
        run: hugo server --disableFastRender -verbose --config config-pdf.yaml & sleep 5 && weasyprint -v http://localhost:1313/dtdocs/index.html ./public/darktable_user_manual.pdf && pkill hugo

      - name: Start an HTTP server
        run: cd public && python -m http.server 8080 > /dev/null 2>&1 &

      - name: Install linkchecker
        run: sudo apt install python3-pip && sudo pip install LinkChecker

      - name: Run linkchecker
        run: linkchecker --check-extern --no-status http://localhost:8080/
